-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  owner_user_id uuid NOT NULL,
  entity_type USER-DEFINED NOT NULL,
  entity_id text NOT NULL,
  action USER-DEFINED NOT NULL,
  actor_user_id uuid,
  changes_json jsonb,
  ip_address inet,
  user_agent text,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_owner_user_id_fkey FOREIGN KEY (owner_user_id) REFERENCES public.profiles(user_id),
  CONSTRAINT audit_logs_actor_user_id_fkey FOREIGN KEY (actor_user_id) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.cases (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  owner_user_id uuid NOT NULL,
  title text NOT NULL,
  question text,
  summary text,
  status USER-DEFINED NOT NULL DEFAULT 'draft'::"CaseStatus",
  priority USER-DEFINED NOT NULL DEFAULT 'normal'::"CasePriority",
  tags ARRAY DEFAULT ARRAY[]::text[],
  last_ingested_at timestamp with time zone,
  last_run_at timestamp with time zone,
  last_published_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone NOT NULL,
  archived_at timestamp with time zone,
  CONSTRAINT cases_pkey PRIMARY KEY (id),
  CONSTRAINT cases_owner_user_id_fkey FOREIGN KEY (owner_user_id) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.chunks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  document_id uuid NOT NULL,
  case_id uuid NOT NULL,
  owner_user_id uuid NOT NULL,
  chunk_index integer NOT NULL,
  content text NOT NULL,
  token_count integer,
  embedding USER-DEFINED,
  metadata_json jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chunks_pkey PRIMARY KEY (id),
  CONSTRAINT chunks_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.documents(id),
  CONSTRAINT chunks_case_id_fkey FOREIGN KEY (case_id) REFERENCES public.cases(id),
  CONSTRAINT chunks_owner_user_id_fkey FOREIGN KEY (owner_user_id) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.documents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  source_id uuid NOT NULL,
  case_id uuid NOT NULL,
  owner_user_id uuid NOT NULL,
  version integer NOT NULL DEFAULT 1,
  parser text,
  language text,
  mime_type text,
  content_text text,
  char_count integer,
  token_count integer,
  metadata_json jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone NOT NULL,
  CONSTRAINT documents_pkey PRIMARY KEY (id),
  CONSTRAINT documents_source_id_fkey FOREIGN KEY (source_id) REFERENCES public.sources(id),
  CONSTRAINT documents_case_id_fkey FOREIGN KEY (case_id) REFERENCES public.cases(id),
  CONSTRAINT documents_owner_user_id_fkey FOREIGN KEY (owner_user_id) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.ingestion_attempts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  source_id uuid NOT NULL,
  case_id uuid NOT NULL,
  owner_user_id uuid NOT NULL,
  attempt_no integer NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'queued'::"IngestionAttemptStatus",
  stage USER-DEFINED,
  error_message text,
  metrics_json jsonb,
  started_at timestamp with time zone,
  finished_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone NOT NULL,
  CONSTRAINT ingestion_attempts_pkey PRIMARY KEY (id),
  CONSTRAINT ingestion_attempts_source_id_fkey FOREIGN KEY (source_id) REFERENCES public.sources(id),
  CONSTRAINT ingestion_attempts_case_id_fkey FOREIGN KEY (case_id) REFERENCES public.cases(id),
  CONSTRAINT ingestion_attempts_owner_user_id_fkey FOREIGN KEY (owner_user_id) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.jobs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  owner_user_id uuid NOT NULL,
  case_id uuid,
  source_id uuid,
  run_id uuid,
  job_type USER-DEFINED NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'queued'::"JobStatus",
  priority integer NOT NULL DEFAULT 100,
  payload_json jsonb,
  scheduled_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  locked_at timestamp with time zone,
  finished_at timestamp with time zone,
  worker_id text,
  attempts integer NOT NULL DEFAULT 0,
  max_attempts integer NOT NULL DEFAULT 3,
  last_error text,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone NOT NULL,
  CONSTRAINT jobs_pkey PRIMARY KEY (id),
  CONSTRAINT jobs_owner_user_id_fkey FOREIGN KEY (owner_user_id) REFERENCES public.profiles(user_id),
  CONSTRAINT jobs_case_id_fkey FOREIGN KEY (case_id) REFERENCES public.cases(id),
  CONSTRAINT jobs_source_id_fkey FOREIGN KEY (source_id) REFERENCES public.sources(id),
  CONSTRAINT jobs_run_id_fkey FOREIGN KEY (run_id) REFERENCES public.runs(id)
);
CREATE TABLE public.profiles (
  user_id uuid NOT NULL,
  email USER-DEFINED,
  display_name text,
  avatar_url text,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone NOT NULL,
  CONSTRAINT profiles_pkey PRIMARY KEY (user_id)
);
CREATE TABLE public.report_citations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  report_version_id uuid NOT NULL,
  owner_user_id uuid NOT NULL,
  claim_id uuid,
  source_id uuid NOT NULL,
  document_id uuid,
  chunk_id uuid,
  citation_label text,
  excerpt text,
  location_json jsonb,
  confidence numeric,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT report_citations_pkey PRIMARY KEY (id),
  CONSTRAINT report_citations_report_version_id_fkey FOREIGN KEY (report_version_id) REFERENCES public.report_versions(id),
  CONSTRAINT report_citations_owner_user_id_fkey FOREIGN KEY (owner_user_id) REFERENCES public.profiles(user_id),
  CONSTRAINT report_citations_claim_id_fkey FOREIGN KEY (claim_id) REFERENCES public.report_claims(id),
  CONSTRAINT report_citations_source_id_fkey FOREIGN KEY (source_id) REFERENCES public.sources(id),
  CONSTRAINT report_citations_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.documents(id),
  CONSTRAINT report_citations_chunk_id_fkey FOREIGN KEY (chunk_id) REFERENCES public.chunks(id)
);
CREATE TABLE public.report_claims (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  report_version_id uuid NOT NULL,
  owner_user_id uuid NOT NULL,
  claim_index integer NOT NULL,
  section text,
  claim_text text NOT NULL,
  support_score numeric,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone NOT NULL,
  CONSTRAINT report_claims_pkey PRIMARY KEY (id),
  CONSTRAINT report_claims_report_version_id_fkey FOREIGN KEY (report_version_id) REFERENCES public.report_versions(id),
  CONSTRAINT report_claims_owner_user_id_fkey FOREIGN KEY (owner_user_id) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.report_versions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  case_id uuid NOT NULL,
  run_id uuid,
  owner_user_id uuid NOT NULL,
  version_number integer NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'draft'::"ReportVersionStatus",
  title text,
  summary text,
  content_markdown text,
  citations_json jsonb,
  created_by_user_id uuid,
  published_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone NOT NULL,
  archived_at timestamp with time zone,
  CONSTRAINT report_versions_pkey PRIMARY KEY (id),
  CONSTRAINT report_versions_case_id_fkey FOREIGN KEY (case_id) REFERENCES public.cases(id),
  CONSTRAINT report_versions_run_id_fkey FOREIGN KEY (run_id) REFERENCES public.runs(id),
  CONSTRAINT report_versions_owner_user_id_fkey FOREIGN KEY (owner_user_id) REFERENCES public.profiles(user_id),
  CONSTRAINT report_versions_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.run_artifacts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  run_id uuid NOT NULL,
  case_id uuid NOT NULL,
  owner_user_id uuid NOT NULL,
  artifact_type USER-DEFINED NOT NULL,
  title text,
  payload_json jsonb NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT run_artifacts_pkey PRIMARY KEY (id),
  CONSTRAINT run_artifacts_run_id_fkey FOREIGN KEY (run_id) REFERENCES public.runs(id),
  CONSTRAINT run_artifacts_case_id_fkey FOREIGN KEY (case_id) REFERENCES public.cases(id),
  CONSTRAINT run_artifacts_owner_user_id_fkey FOREIGN KEY (owner_user_id) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.run_steps (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  run_id uuid NOT NULL,
  owner_user_id uuid NOT NULL,
  step_key text NOT NULL,
  step_order integer NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'queued'::"RunStepStatus",
  goal text,
  input_json jsonb,
  output_json jsonb,
  error_message text,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  duration_ms integer,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone NOT NULL,
  CONSTRAINT run_steps_pkey PRIMARY KEY (id),
  CONSTRAINT run_steps_run_id_fkey FOREIGN KEY (run_id) REFERENCES public.runs(id),
  CONSTRAINT run_steps_owner_user_id_fkey FOREIGN KEY (owner_user_id) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.runs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  case_id uuid NOT NULL,
  owner_user_id uuid NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'queued'::"RunStatus",
  current_step text,
  needs_review boolean NOT NULL DEFAULT false,
  review_summary text,
  checkpoint_ref text,
  checkpoint_at timestamp with time zone,
  triggered_by_user_id uuid,
  approved_by_user_id uuid,
  error_message text,
  started_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed_at timestamp with time zone,
  duration_ms integer,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone NOT NULL,
  approved_at timestamp with time zone,
  CONSTRAINT runs_pkey PRIMARY KEY (id),
  CONSTRAINT runs_case_id_fkey FOREIGN KEY (case_id) REFERENCES public.cases(id),
  CONSTRAINT runs_owner_user_id_fkey FOREIGN KEY (owner_user_id) REFERENCES public.profiles(user_id),
  CONSTRAINT runs_triggered_by_user_id_fkey FOREIGN KEY (triggered_by_user_id) REFERENCES public.profiles(user_id),
  CONSTRAINT runs_approved_by_user_id_fkey FOREIGN KEY (approved_by_user_id) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.sources (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  case_id uuid NOT NULL,
  owner_user_id uuid NOT NULL,
  source_type USER-DEFINED NOT NULL,
  title text,
  url text,
  storage_path text,
  note_text text,
  content_hash text,
  status USER-DEFINED NOT NULL DEFAULT 'pending'::"SourceStatus",
  error_message text,
  metadata_json jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone NOT NULL,
  archived_at timestamp with time zone,
  CONSTRAINT sources_pkey PRIMARY KEY (id),
  CONSTRAINT sources_case_id_fkey FOREIGN KEY (case_id) REFERENCES public.cases(id),
  CONSTRAINT sources_owner_user_id_fkey FOREIGN KEY (owner_user_id) REFERENCES public.profiles(user_id)
);